# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/luongtoi/Documents/Projects/CasioEmuMsvc/CasioEmuMsvc/SDL_image/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/luongtoi/Documents/Projects/CasioEmuMsvc/CasioEmuMsvc/SDL_image/cmake/PrivateSdlFunctions.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))

/Users/luongtoi/Documents/Projects/CasioEmuMsvc/CasioEmuMsvc/build-ios/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/bin/cmake -S/Users/luongtoi/Documents/Projects/CasioEmuMsvc/CasioEmuMsvc -B/Users/luongtoi/Documents/Projects/CasioEmuMsvc/CasioEmuMsvc/build-ios
