# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/luongtoi/Documents/Projects/CasioEmuMsvc/CasioEmuMsvc/CasioEmuMsvc/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CPack.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Modules/CPackComponent.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake/Templates/CPackConfig.cmake.in))

/Users/luongtoi/Documents/Projects/CasioEmuMsvc/CasioEmuMsvc/build-ios/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/bin/cmake -S/Users/luongtoi/Documents/Projects/CasioEmuMsvc/CasioEmuMsvc -B/Users/luongtoi/Documents/Projects/CasioEmuMsvc/CasioEmuMsvc/build-ios
